-- Mot de passe par defaut : Password123
INSERT INTO students(first_name, last_name, email, password_hash) VALUES

('Andrianjafy',      NULL, 'andrianjafy@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Razafindrakoto',   NULL, 'razafindrakoto@mail.hei.school',   '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Ratsimbazafy',     NULL, 'ratsimbazafy@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rakotomanga',      NULL, 'rakotomanga@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Ranaivojaona',     NULL, 'ranaivojaona@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Ramilison',        NULL, 'ramilison@mail.hei.school',        '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Razanamparany',    NULL, 'razanamparany@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rakotomalala',     NULL, 'rakotomalala@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Raharimanana',     NULL, 'raharimanana@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Randrianasolo',    NULL, 'randrianasolo@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Razafitrimo',      NULL, 'razafitrimo@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rakotonirina',     NULL, 'rakotonirina@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rasoamananjara',   NULL, 'rasoamananjara@mail.hei.school',   '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Ralaimongo',       NULL, 'ralaimongo@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Ramanantsoa',      NULL, 'ramanantsoa@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),

('Mamy',       'Rakoto',            'mamy@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Sitraka',    'Andriamahazo',      'sitraka@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Fanja',      'Rajerison',         'fanja@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Nirinasoa',  'Randriamandrato',   'nirinasoa@mail.hei.school',  '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Tojo',       'Ravelomanantsoa',   'tojo@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Hasina',     'Rajaonarivelo',     'hasina@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Nantenaina', 'Rakotondrabe',      'nantenaina@mail.hei.school', '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Tahina',     'Ratsimandresy',     'tahina@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Faly',       'Radavidrason',      'faly@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Volana',     'Razafindramboa',    'volana@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Lova',       'Ramanandraibe',     'lova@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Tiana',      'Rakotonavalona',    'tiana@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rija',       'Randrianarison',    'rija@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Koloina',    'Andrianainarivelo', 'koloina@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Rindra',     'Rafanomezantsoa',   'rindra@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Faniry',     'Rakotoarimanana',   'faniry@mail.hei.school',     '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),

('Christian', 'Albert',  'christian@mail.hei.school',  '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Jean',      'Michel',  'jean@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Eric',      'Justin',  'eric@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Patrick',   'David',   'patrick@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Josiane',   'Lucas',   'josiane@mail.hei.school',    '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Aina',      'Charles', 'aina@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Fano',      'Daniel',  'fano@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Mialy',     'Thomas',  'mialy@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Hery',      'Pascal',  'hery@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Tsiry',     'Laurent', 'tsiry@mail.hei.school',      '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Feno',      'Joseph',  'feno@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Niry',      'Martin',  'niry@mail.hei.school',       '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Harinaivo', 'Pierre',  'harinaivo@mail.hei.school',  '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG'),
('Lalatiana', 'Paul',    'lalatiana@mail.hei.school',  '$2b$10$RmZPegRqu.PLzU1E9wdAs.chtAaSnqx.7OloxamDnl5tSl24ySCZG')
ON CONFLICT (email) DO NOTHING;
